---
TemplateDir: design
PreviewDir: preview
StaticDir: static
Verbose: true
Twig:
  auto_reload: true
  cache: cache
Tasks:
#  - CleanTask:
#      paths:
#        - cache
#        - .sass-cache
  - CleanPreviewTask:
#  - CopyDesignTask:
#      rsync: false
  - CompileScssTask:
      force: false
      compass: true
      paths:
        - design/static/scss:design/static/css
  - ChmodReadWriteTask:
  - RenderPreviewTask:
      templateDirs:
        - design
  - CompileMessageTask:
      paths:
        - design
  - CopyTask:
      paths:
        - design/static:preview/static
